version: '3.8'
services:
  localhost:
    image: postgres:latest
    container_name: localhost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: db_project_2
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile.py
    container_name: app
    environment:
      DATABASE_URL: postgres://postgres:123456789@localhost:5432/db_project_2
    depends_on:
      - localhost