dbt_dskola_project:
  outputs:
    dev:
      dbname: db_project_2
      host: localhost
      pass: '123456789'
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
